CREATE SCHEMA db;

use db;

CREATE TABLE annuaire_sante (
    id_type varchar(1),
    id varchar(11),
    id_nat varchar(12),
    civility_practice_code varchar(2),
    civility_practice_label varchar(10),
    civility_code varchar(4),
    civility_label varchar(12),
    lastname varchar(60),
    firstname varchar(60),
    profession_code varchar(2),
    profession_label varchar(34),
    professional_category_code varchar(1),
    professional_category_label varchar(9),
    know_how_type_code varchar(3),
    know_how_type_label varchar(21),
    know_how_code varchar(5),
    know_how_label varchar(66),
    practice_mode_code varchar(1),
    practice_mode_label varchar(10),
    siren_number varchar(14),
    siret_number varchar(9),
    finess_number varchar(9),
    finess_legal_number varchar(9),
    technical_id varchar(18),
    company_name varchar(164),
    commercial_sign varchar(50),
    recipient_supplement varchar(38),
    geographic_point_supplement varchar(38),
    street_number varchar(5),
    street_repeat_index varchar(3),
    street_type_code varchar(4),
    street_type_label varchar(28),
    street_label varchar(38),
    distribution_mention varchar(38),
    cedex_office varchar(38),
    zip_code varchar(5),
    town_code varchar(5),
    town_label varchar(45),
    country_code varchar(5),
    country_label varchar(8),
    phone varchar(15),
    phone2 varchar(15),
    fax varchar(15),
    email varchar(512),
    county_code varchar(5),
    county_label varchar(45),
    old_id varchar(15),
    registration_authority varchar(21),
    sector_code varchar(4),
    sector_label varchar(53),
    pharmacists_table_section_code varchar(2),
    pharmacists_table_section_label varchar(240)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;